


#spring datasource & jpa config
spring:
  mvc:
    servlet:
      load-on-startup=1:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost/demo
#    username: root
#    password: c225cc
    url: jdbc:mysql://101.43.208.136/2020011236
    username: 2020011236
    password: NxcKw6kNaEt2jxKW
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialectorg: hibernate.dialect.MySQL8Dialect

#mybatis-plus config
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/**/*.xml
