
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.208.136:3306/2020011236
    username: 2020011236
    password: NxcKw6kNaEt2jxKW
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialectorg: hibernate.dialect.MySQL8Dialect

