


#spring datasource & jpa config
spring:
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  mvc:
    servlet:
      load-on-startup=1:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://101.43.208.136/2020011236
    username: 2020011236
    password: NxcKw6kNaEt2jxKW
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialectorg: hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: 101.43.208.136
      port: 6379
      password: c225cc
      database: 0
  session:
    store-type: redis


#mybatis-plus config
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:mapper/**/*.xml

#images
image:
  endpoint: http:/101.43.208.136:9090/mall/


#Minio
minio:
  endpoint: http://101.43.208.136:9090
  bucketName: mall
  accessKey: minioadmin
  secretKey: minioadmin

